import sys

def advance_good(mask, length, RM, FULL, THRESH):
    # advance over `length` good cells; return window mask at the last one
    cnt = 0
    while cnt < length:
        if mask == 0 or mask == FULL:
            return mask
        if mask & RM:
            mask = ((mask << 1) | 1) & FULL
            cnt += 1
            if length - cnt >= THRESH:
                return FULL
        else:
            mask = (mask << 1) & FULL
            cnt += 1
    return mask

def main():
    data = sys.stdin.buffer.read().split()
    if not data:
        return
    N = int(data[0]); M = int(data[1]); A = int(data[2]); B = int(data[3])
    p = 4
    intervals = []
    for _ in range(M):
        l = int(data[p]); r = int(data[p + 1]); p += 2
        intervals.append((l, r))

    # Fixed step size: forced path 1, 1+A, 1+2A, ...
    if A == B:
        ok = ((N - 1) % A == 0)
        if ok:
            for l, r in intervals:
                k = (l + A - 2) // A          # ceil((l-1)/A)
                pos = 1 + k * A
                if pos <= r:
                    ok = False
                    break
        sys.stdout.write("Yes\n" if ok else "No\n")
        return

    # A < B
    # Merge touching bad intervals into maximal contiguous bad runs.
    merged = []
    for l, r in intervals:
        if merged and l <= merged[-1][1] + 1:
            if r > merged[-1][1]:
                merged[-1][1] = r
        else:
            merged.append([l, r])

    # A contiguous bad run of length >= B can never be crossed.
    for l, r in merged:
        if r - l + 1 >= B:
            sys.stdout.write("No\n")
            return

    FULL = (1 << B) - 1
    RM = (1 << B) - (1 << (A - 1))   # bits A-1 .. B-1
    C0 = A * A - A                   # conductor of semigroup generated by {A, A+1}
    THRESH = C0 + B - 1

    mask = 1   # bit t = reachable(cur - t); start at position 1
    cur = 1
    for l, r in merged:
        hi = l - 1
        if hi > cur:
            mask = advance_good(mask, hi - cur, RM, FULL, THRESH)
            cur = hi
        for _ in range(r - l + 1):    # walk over bad cells
            mask = (mask << 1) & FULL
        cur = r

    if N > cur:
        mask = advance_good(mask, N - cur, RM, FULL, THRESH)
        cur = N

    sys.stdout.write("Yes\n" if (mask & 1) else "No\n")

main()